//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Devices
    {
        public int ID { get; set; }
        public string SerialNo { get; set; }
        public string ModelCode { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> RegistDateTime { get; set; }
    
        public virtual T_Customers T_Customers { get; set; }
    }
}
